# Generated by Django 5.1.1 on 2024-09-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0002_remove_solution_name1_remove_solution_name2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='cover_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='textbook',
            name='number_of_parts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
