# Generated by Django 5.1.1 on 2024-09-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0003_textbook_cover_color_textbook_number_of_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='english_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
