# Generated by Django 5.1.1 on 2024-09-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0004_subject_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='book_series',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
