# Generated by Django 5.1.1 on 2024-09-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0005_textbook_book_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='textbook',
        ),
    ]
