# Generated by Django 5.1.1 on 2024-09-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0007_solution_name_3_solution_name_4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='name_3',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='name_4',
        ),
    ]
